name: Daily Paper Tracker

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch: 

jobs:
  run-scraper-and-email:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 3.10 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装官方 arXiv 依赖包 (新增这一步)
        run: pip install arxiv

      - name: 执行 Python 脚本并发送邮件
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python scraper.py
